#!/bin/bash

# chkconfig: 2345 99 10
# description: oauthd daemon

# Source function library.
. /etc/init.d/functions


start() {
        echo -n "Starting oauthd: "
        oauthd start
        return $?
}

stop() {
        echo -n "Shutting down oauthd: "
        oauthd stop
        return $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        oauthd status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: oauthd {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
